"""
config.py — Central configuration file.
Edit the values here before deploying the bot.
"""

# ── Telegram Bot Token (from @BotFather) ─────────────────────────────────────
BOT_TOKEN = "8719706162:AAG632rzq9qgBnb1h5Lcp2nG4bXaqF-xWH8"

# ── Admin Telegram user_id ────────────────────────────────────────────────────
ADMIN_ID = 6342616493

# ── OpenAI API key  (set here OR export OPENAI_API_KEY env variable) ─────────
OPENAI_API_KEY = "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"

# ── Bot username (without @) — shown in watermark ────────────────────────────
BOT_USERNAME = "Pdscanner_bot"

# ── Watermark text ────────────────────────────────────────────────────────────
WATERMARK_TEXT = f"📄 Generated by @{BOT_USERNAME} — Upgrade to Premium!"

# ── Database file path ────────────────────────────────────────────────────────
DB_PATH = "scanner_bot.db"

# ── Default scan settings (can be changed per user in future versions) ────────
DEFAULT_FILTER     = "magic_color"   # 'magic_color' | 'bw' | 'none'
DEFAULT_MODE       = "a4"            # 'a4' | 'passport' | 'id_card' | 'photo'
DEFAULT_AUTO_CROP  = True
