"""
utils.py — Core image processing, PDF generation, watermarking, and AI utilities.

Libraries used:
  - OpenCV  : edge detection, perspective warp, thresholding
  - Pillow  : watermark overlay, color adjustments
  - img2pdf : lossless image-to-PDF conversion
  - openai  : GPT-4o vision for document Q&A / translation
"""

import io
import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageEnhance, ImageFilter
import img2pdf
import logging
import base64
import os
from openai import AsyncOpenAI

logger = logging.getLogger(__name__)

# ── OpenAI client (set OPENAI_API_KEY in environment or config.py) ──────────
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "YOUR_OPENAI_API_KEY_HERE")
openai_client = AsyncOpenAI(api_key=OPENAI_API_KEY)

# ── Watermark text shown on Free-plan PDFs ───────────────────────────────────
WATERMARK_TEXT = "📄 Generated by @YourBotName — Upgrade to Premium!"


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 1 — AUTO-CROP: Edge detection + perspective transformation
# ─────────────────────────────────────────────────────────────────────────────

def order_points(pts: np.ndarray) -> np.ndarray:
    """
    Sort 4 corner points into [top-left, top-right, bottom-right, bottom-left]
    order required by cv2.getPerspectiveTransform.
    """
    rect = np.zeros((4, 2), dtype="float32")
    s = pts.sum(axis=1)
    rect[0] = pts[np.argmin(s)]   # top-left  (smallest x+y)
    rect[2] = pts[np.argmax(s)]   # bot-right (largest x+y)
    diff = np.diff(pts, axis=1)
    rect[1] = pts[np.argmin(diff)]  # top-right
    rect[3] = pts[np.argmax(diff)]  # bot-left
    return rect


def four_point_transform(image: np.ndarray, pts: np.ndarray) -> np.ndarray:
    """
    Apply a perspective (bird's-eye) transform to straighten a document
    given its four corner points.
    """
    rect = order_points(pts)
    (tl, tr, br, bl) = rect

    # Compute the width of the new image
    widthA  = np.linalg.norm(br - bl)
    widthB  = np.linalg.norm(tr - tl)
    maxW    = max(int(widthA), int(widthB))

    # Compute the height of the new image
    heightA = np.linalg.norm(tr - br)
    heightB = np.linalg.norm(tl - bl)
    maxH    = max(int(heightA), int(heightB))

    # Destination points for the "top-down" view
    dst = np.array([
        [0,        0       ],
        [maxW - 1, 0       ],
        [maxW - 1, maxH - 1],
        [0,        maxH - 1],
    ], dtype="float32")

    M = cv2.getPerspectiveTransform(rect, dst)
    return cv2.warpPerspective(image, M, (maxW, maxH))


def auto_crop(img_bytes: bytes) -> bytes:
    """
    Detect the document edges in the image and warp it to a flat rectangle.
    Falls back to the original image if no clear contour is found.

    Returns processed image as JPEG bytes.
    """
    # Decode bytes → numpy array
    nparr = np.frombuffer(img_bytes, np.uint8)
    img   = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    orig  = img.copy()

    # Pre-process for contour detection
    gray    = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edged   = cv2.Canny(blurred, 75, 200)

    # Find contours and pick the largest 4-point one (likely the document)
    contours, _ = cv2.findContours(edged, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    contours     = sorted(contours, key=cv2.contourArea, reverse=True)[:5]

    screen_cnt = None
    for c in contours:
        peri   = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.02 * peri, True)
        if len(approx) == 4:
            screen_cnt = approx
            break

    if screen_cnt is None:
        logger.warning("⚠️  No 4-point contour found; returning original image.")
        result = orig
    else:
        result = four_point_transform(orig, screen_cnt.reshape(4, 2))

    _, buf = cv2.imencode(".jpg", result, [cv2.IMWRITE_JPEG_QUALITY, 95])
    return buf.tobytes()


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 2 — FILTERS
# ─────────────────────────────────────────────────────────────────────────────

def apply_magic_color(img_bytes: bytes) -> bytes:
    """
    'Magic Color' filter: sharpen edges, boost contrast/saturation so
    printed text pops while keeping photos looking natural.
    """
    pil_img = Image.open(io.BytesIO(img_bytes)).convert("RGB")

    # Slightly sharpen
    pil_img = pil_img.filter(ImageFilter.SHARPEN)

    # Boost contrast
    pil_img = ImageEnhance.Contrast(pil_img).enhance(1.4)

    # Boost saturation (makes coloured headers / logos vivid)
    pil_img = ImageEnhance.Color(pil_img).enhance(1.2)

    # Boost sharpness one more time for crisp text
    pil_img = ImageEnhance.Sharpness(pil_img).enhance(2.0)

    buf = io.BytesIO()
    pil_img.save(buf, format="JPEG", quality=95)
    return buf.getvalue()


def apply_bw_filter(img_bytes: bytes) -> bytes:
    """
    'B&W' (Black & White / Adaptive Threshold) filter: converts the image to
    a clean black-and-white scan ideal for text-heavy documents.
    Uses OpenCV's adaptive threshold to handle uneven lighting gracefully.
    """
    nparr = np.frombuffer(img_bytes, np.uint8)
    img   = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    gray  = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Adaptive threshold: each pixel is thresholded based on a local area
    thresh = cv2.adaptiveThreshold(
        gray, 255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY,
        blockSize=11, C=7
    )

    _, buf = cv2.imencode(".jpg", thresh, [cv2.IMWRITE_JPEG_QUALITY, 95])
    return buf.tobytes()


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 3 — WATERMARK
# ─────────────────────────────────────────────────────────────────────────────

def add_watermark(img_bytes: bytes, text: str = WATERMARK_TEXT) -> bytes:
    """
    Draw a semi-transparent watermark banner at the bottom of the image.
    Used for Free-plan users only.
    """
    pil_img = Image.open(io.BytesIO(img_bytes)).convert("RGBA")
    w, h    = pil_img.size

    # Create a transparent overlay the full width of the image
    overlay = Image.new("RGBA", pil_img.size, (0, 0, 0, 0))
    draw    = ImageDraw.Draw(overlay)

    # Banner height ~4% of image height (min 30px)
    banner_h = max(30, int(h * 0.04))
    draw.rectangle([(0, h - banner_h), (w, h)], fill=(0, 0, 0, 160))

    # Try to use a default font; fall back to PIL's built-in if unavailable
    try:
        font_size = max(12, banner_h - 8)
        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", font_size)
    except Exception:
        font = ImageFont.load_default()

    # Centre the text within the banner
    bbox    = draw.textbbox((0, 0), text, font=font)
    text_w  = bbox[2] - bbox[0]
    text_x  = (w - text_w) // 2
    text_y  = h - banner_h + (banner_h - (bbox[3] - bbox[1])) // 2
    draw.text((text_x, text_y), text, font=font, fill=(255, 255, 255, 230))

    # Composite overlay onto original image
    combined = Image.alpha_composite(pil_img, overlay).convert("RGB")
    buf      = io.BytesIO()
    combined.save(buf, format="JPEG", quality=95)
    return buf.getvalue()


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 4 — PDF GENERATION
# ─────────────────────────────────────────────────────────────────────────────

def images_to_pdf(image_bytes_list: list[bytes]) -> bytes:
    """
    Convert a list of JPEG/PNG image byte-strings into a single PDF using img2pdf.
    Returns the raw PDF bytes ready to be sent as a Telegram document.
    """
    pdf_bytes = img2pdf.convert(image_bytes_list)
    return pdf_bytes


# ─────────────────────────────────────────────────────────────────────────────
#  FULL PIPELINE — single convenience function
# ─────────────────────────────────────────────────────────────────────────────

def process_image(
    img_bytes: bytes,
    mode: str = "a4",
    filter_type: str = "magic_color",
    apply_crop: bool = True,
    watermark: bool = True,
) -> bytes:
    """
    Run the complete scan pipeline on a single image:
      1. Auto-crop (perspective fix)
      2. Apply selected filter
      3. Optionally add watermark (Free plan)

    Parameters
    ----------
    img_bytes   : raw image bytes received from Telegram
    mode        : 'a4' | 'passport' | 'id_card' | 'photo' — reserved for
                  future aspect-ratio enforcement; currently informational
    filter_type : 'magic_color' | 'bw' | 'none'
    apply_crop  : whether to run auto-crop
    watermark   : whether to stamp the free-plan watermark

    Returns processed image bytes (JPEG).
    """
    data = img_bytes

    if apply_crop:
        data = auto_crop(data)

    if filter_type == "magic_color":
        data = apply_magic_color(data)
    elif filter_type == "bw":
        data = apply_bw_filter(data)
    # 'none' → no filter applied

    if watermark:
        data = add_watermark(data)

    return data


# ─────────────────────────────────────────────────────────────────────────────
#  AI ASSISTANT — OpenAI GPT-4o Vision
# ─────────────────────────────────────────────────────────────────────────────

async def ask_ai_about_image(img_bytes: bytes, user_question: str) -> str:
    """
    Send the scanned image to GPT-4o along with the user's question.
    Handles both document Q&A and translation requests.

    Returns the AI's text response.
    """
    # Encode image to base64 for the API
    b64_image = base64.b64encode(img_bytes).decode("utf-8")

    try:
        response = await openai_client.chat.completions.create(
            model="gpt-4o",
            max_tokens=1500,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a helpful document assistant. "
                        "The user has scanned a document and may ask you to summarise it, "
                        "answer questions about its content, or translate text from it. "
                        "Be concise, professional, and accurate."
                    )
                },
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{b64_image}",
                                "detail": "high"
                            }
                        },
                        {
                            "type": "text",
                            "text": user_question
                        }
                    ]
                }
            ]
        )
        return response.choices[0].message.content.strip()

    except Exception as e:
        logger.error(f"OpenAI API error: {e}")
        return (
            "⚠️ Sorry, the AI assistant is currently unavailable. "
            "Please try again later."
        )
